# Generated by Django 2.0.2 on 2018-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologger', '0002_auto_20180207_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='accuracy',
            field=models.FloatField(),
        ),
    ]
