# Generated by Django 2.0.2 on 2018-02-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologger', '0003_auto_20180207_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='accuracy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
